# Generated by Django 3.2.6 on 2021-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='sub_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
