# Generated by Django 3.2.6 on 2021-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211127_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
