# Generated by Django 3.2.6 on 2021-12-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tempkfir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempKfir',
        ),
    ]
