# Generated by Django 3.2.6 on 2021-11-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bla',
            new_name='Temp',
        ),
    ]
