# Generated by Django 3.2.6 on 2021-11-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='temp',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tempgeneral'),
        ),
        migrations.AddField(
            model_name='temp',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.temptravel'),
        ),
    ]
