# Generated by Django 3.2.6 on 2021-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_itinerarycategory_itineraryplanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplanner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
