# Generated by Django 3.2.6 on 2021-11-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211127_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='body',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='general',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='header',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='sub_subject',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='travel',
        ),
    ]
