# Generated by Django 3.2.6 on 2021-12-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_create_temp_kfir_again'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempKfir',
        ),
    ]
