# Generated by Django 2.2.10 on 2021-11-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_bla_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='header',
            new_name='sub_subject',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='name',
            new_name='subject',
        ),
    ]
