# Generated by Django 3.2.6 on 2021-12-10 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_temp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp2',
            name='categroy',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='user',
        ),
        migrations.AddField(
            model_name='temp2',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='temp2',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='temp2',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='temp2',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='temp2',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
