# Generated by Django 3.2.6 on 2021-11-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211127_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tempgeneral'),
        ),
        migrations.AddField(
            model_name='temp',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.temptravel'),
        ),
    ]
