# Generated by Django 3.2.6 on 2021-12-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20211210_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp2',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='subject',
        ),
        migrations.AddField(
            model_name='temp2',
            name='categroy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.itinerarycategory'),
        ),
        migrations.AddField(
            model_name='temp2',
            name='destination',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='temp2',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp2',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp2',
            name='travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temp2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
