# Generated by Django 3.2.6 on 2021-11-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211127_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='general',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='travel',
        ),
        migrations.AddField(
            model_name='tempgeneral',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.temp'),
        ),
        migrations.AddField(
            model_name='temptravel',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.temp'),
        ),
    ]
