# Generated by Django 3.2.6 on 2021-12-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_create_temp_vova'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempVova',
        ),
    ]
