# Generated by Django 3.2.6 on 2021-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211127_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempgeneral',
            name='general',
        ),
        migrations.RemoveField(
            model_name='temptravel',
            name='travel',
        ),
    ]
