# Generated by Django 3.2.6 on 2021-12-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_temp2_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp2',
            name='user',
        ),
    ]
