# Generated by Django 3.2.6 on 2021-12-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_temp2_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp2',
            old_name='categroy',
            new_name='category',
        ),
    ]
