# Generated by Django 3.2.6 on 2021-12-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_rename_categroy_temp2_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryplanner',
            old_name='categroy',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Temp2',
        ),
    ]
