# Generated by Django 3.2.6 on 2021-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
