# Generated by Django 3.2.6 on 2021-12-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_add_id_to_AboutUs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempTest',
        ),
    ]
