# Generated by Django 3.2.6 on 2021-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_add_id_to_AboutUs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarycategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
