# Generated by Django 3.2.6 on 2021-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_TempTest_edit_UserReviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
