# Generated by Django 3.2.6 on 2021-12-10 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20211210_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplanner',
            name='travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
