# Generated by Django 3.2.6 on 2021-12-05 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tempcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='tempcontact',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tempcontact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tempcontact',
            name='subject',
        ),
        migrations.AddField(
            model_name='tempcontact',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
    ]
