# Generated by Django 3.2.6 on 2021-12-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211205_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.DeleteModel(
            name='TempC',
        ),
        migrations.DeleteModel(
            name='TempContact',
        ),
        migrations.DeleteModel(
            name='TempGeneral',
        ),
        migrations.DeleteModel(
            name='TempTravel',
        ),
    ]
