# Generated by Django 3.2.6 on 2021-12-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_create_UserReviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('culture', models.BooleanField(default=False)),
                ('outdoors', models.BooleanField(default=False)),
                ('beaches', models.BooleanField(default=False)),
                ('shopping', models.BooleanField(default=False)),
                ('museums', models.BooleanField(default=False)),
                ('restaurants', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryPlanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('destination', models.CharField(max_length=254)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.itinerarycategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
