# Generated by Django 3.2.6 on 2021-12-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_create_ItineraryPlanner_ItineraryCategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryplanner',
            name='category',
        ),
    ]
