# Generated by Django 3.2.6 on 2021-12-05 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_temp'),
    ]

