# Generated by Django 3.2.6 on 2021-12-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_alter_itineraryplanner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplanner',
            name='travelers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
