# Generated by Django 3.2.6 on 2021-12-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_edit_ItineraryPlanner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='home_contact',
        ),
    ]
