# Generated by Django 3.2.6 on 2021-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_edit_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
