# Generated by Django 3.2.6 on 2021-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_edit_ItineraryPlanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryplanner',
            name='travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
