# Generated by Django 3.2.6 on 2021-12-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
