# Generated by Django 3.2.6 on 2021-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_itineraryplanner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplanner',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
