# Generated by Django 3.2.6 on 2021-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_edit_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, default=(('General', 'General'), ('Complaint', 'Complaint')), max_length=2),
        ),
    ]
