# Generated by Django 3.2.6 on 2021-12-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_edit_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, choices=[('general', 'GENERAL'), ('complaint', 'COMPLAINT')], default='', max_length=9),
        ),
    ]
