# Generated by Django 3.2.6 on 2021-12-15 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_edit_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.TextField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='', max_length=500)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
