# Generated by Django 3.2.6 on 2021-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_creare_Career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('1', 'GENERAL'), ('2', 'COMPLAINT')], default='1', max_length=9),
        ),
    ]
