# Generated by Django 3.2.6 on 2021-12-10 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_alter_itineraryplanner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryplanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.itinerarycategory'),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
