# Generated by Django 3.2.6 on 2021-12-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-vote_ratio', '-vote_total', 'title'],
            },
        ),
    ]
