# Generated by Django 3.2.6 on 2021-12-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_auto_20211210_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarycategory',
            name='beaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='culture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='museums',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='outdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='restaurants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='shopping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itineraryplanner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
