# Generated by Django 3.2.6 on 2021-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='choice',
            field=models.CharField(choices=[('Very good', 'Very good'), ('Good', 'Good'), ('Mediocre', 'Mediocre'), ('Bad', 'Bad'), ('Very Bad', 'Very Bad')], max_length=200),
        ),
    ]
