# Generated by Django 3.2.6 on 2021-12-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211211_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarycategory',
            name='user',
        ),
    ]
