# Generated by Django 3.2.6 on 2021-12-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_feedback_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='choice',
            new_name='feedback',
        ),
    ]
