# Generated by Django 3.2.6 on 2021-12-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_itinerarycategory_id'),
        ('home', '0025_rename_choice_feedback_feedback'),
    ]

    operations = [
    ]
