# Generated by Django 3.2.6 on 2021-12-15 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_edit_ContactUs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('Very good', 'Very good'), ('Good', 'Good'), ('Mediocre', 'Mediocre'), ('Bad', 'Bad'), ('Very Bad', 'Very Bad')], max_length=200)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
