# Generated by Django 3.2.6 on 2021-12-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_merge_20211211_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
