# Generated by Django 3.2.6 on 2021-12-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_add_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
