# Generated by Django 3.2.6 on 2021-12-16 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_edit_ContactUs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
