# Generated by Django 3.2.6 on 2021-12-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_edit_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types_users', models.CharField(max_length=100)),
                ('num_users', models.IntegerField()),
            ],
        ),
    ]
