# Generated by Django 3.2.6 on 2021-12-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_create_Travels_Places_Travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
