# Generated by Django 3.2.6 on 2021-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_update_ItineraryCategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryplanner',
            name='session_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
