# Generated by Django 3.2.6 on 2021-12-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('home', '0033_update_ItineraryPlanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryplanner',
            name='session_id',
        ),
        migrations.AddField(
            model_name='itineraryplanner',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
